### ISSUE TITLE
构建时拉取静态文件的问题

### ISSUE THREAD

**Issue by LynxCatTheThird** [EmptyDreams/hexo-swpp#3]
![image](https://github.com/EmptyDreams/hexo-swpp/assets/103188954/f1b8be5a-4324-43e4-80ee-290dea115c3c)

1. 从 StaticFile 与 BootCDN 上拉取资源时会出现大量的超时错误，然而我的 timeout 是 5000……

2. 从对象存储上拉取东西总是出错，这个该怎么设置？

```js
// sw-rules.js
module.exports.config = {
    serviceWorker: {
        escape: 0,
        cacheName: 'LCTTBlogCache'
    },
    register: {
        onsuccess: undefined,
        onerror: () => console.error('Service Worker 注册失败，可能是由于您的浏览器不支持该功能！'),
        builder: (root, framework, pluginConfig) => {
            const { onerror, onsuccess } = pluginConfig.register;
            return `
            <script>
                (() => {
                    const sw = navigator.serviceWorker;
                    const error = ${onerror && onerror.toString()};
                    if (!sw?.register('${new URL(root).pathname}sw.js')
                        ${onsuccess ? `?.then(${onsuccess.toString()})` : ''}
                        ?.catch(error)
                    ) error()
                })()
            </script>`;
        }
    },
    dom: {
        onsuccess: () => {
            caches.match(location.href).then(res => {
                if (res)
                    res.json().then(json => {
                        utils && utils.snackbarShow(`已刷新缓存，更新为${json.global + '.' + json.local}版本最新内容`, false, 2000)
                    })
                else
                    console.info('未找到缓存')
            }).catch((error) => console.error("缓存匹配出错", error))
        }
    },
    json: {
        maxHtml: 15,
        charLimit: 1024,
        merge: ['index', 'tags', 'categories'],
        exclude: {
            localhost: [],
            other: []
        }
    },
    external: {
        timeout: 5000,
        concurrencyLimit: 100,
        js: [],
        stable: [],
        replacer: srcUrl => {
            if (srcUrl.startsWith('https://cdn.jsdelivr.net/npm/')) {
                const pathname = new URL(srcUrl).pathname;
                return [
                    srcUrl,
                    `https://cdn.cbd.int/${pathname}`,
                    `https://npm.elemecdn.com/${pathname}`,
                    `https://fastly.jsdelivr.net/npm/${pathname}`,
                ];
            } else {
                return srcUrl;
            }
        }
    }
};

module.exports.cacheRules = {
    simple: {
        clean: true,
        search: false,
        match: (url, $eject) => (url.host.includes('lynx') || url.host.includes('lctt')) && url.pathname.match(/\.(html|js|css|xml)$/), //主站缓存
    },
    cdn: {
        clean: true,
        match: url => [
            // 此处略去部分 CDN 节点
            "cdn.staticfile.net",
            "cdn.bootcdn.net",
        ].includes(url.host) && url.pathname.match(/\.(js|css|woff2|woff|ttf|json|png|jpg|webp)$/), //CDN 缓存
    }
};

module.exports.getSpareUrls = srcUrl => {
    if (srcUrl.startsWith("https://npm.elemecdn.com")) {
        return {
            timeout: 3000,
            list: [srcUrl, `https://fastly.jsdelivr.net/${new URL(srcUrl).pathname}`, `https://cdn.cbd.int/${new URL(srcUrl).pathname}`],
        };
    }
}

module.exports.isMemoryQueue = request => {
    // do something...
}

module.exports.ejectValues = (hexo, rules) => {
    return {
        domain: {
            prefix: "const",
            value: new URL(hexo.config.url).host,
        },
    };
};
```

**Comment by EmptyDreams** [comment]
减小 concurrencyLimit 的值试试，默认 100

**Comment by LynxCatTheThird** [comment]
改成 1 都不行……

补充：jsdelivr、cdnjs 暂未发现有此问题

**Comment by EmptyDreams** [comment]
> 改成 1 都不行……
> 
> 补充：jsdelivr、cdnjs 暂未发现有此问题

更新一下 `hexo-swpp` 的版本，然后使用 `hexo swpp -t` 拉取一下构建的时候拉取不下来的资源试试。

**Comment by LynxCatTheThird** [comment]
似乎仍然不行？

![image](https://github.com/EmptyDreams/hexo-swpp/assets/103188954/5f81832b-5e1b-4ca5-b26e-a34ea611a394)

**Comment by EmptyDreams** [comment]
> 似乎仍然不行？
> 
> ![image](https://private-user-images.githubusercontent.com/103188954/302883725-5f81832b-5e1b-4ca5-b26e-a34ea611a394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDg4NDgsIm5iZiI6MTcwNzMwODU0OCwicGF0aCI6Ii8xMDMxODg5NTQvMzAyODgzNzI1LTVmODE4MzJiLTVlMWItNGNhNS1iMjZlLWEzNGVhNjExYTM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMjIyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDJiZDlkYjJmYjgwMzUwM2FkM2E5ODBlOGU0MGQwZGYzMTkwZTdlY2M1YzcwMmQ0MDE2YjhjYjEwMGMwYzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uo28M9yJHOoA4YPVKWfkf7zuKZA3nweuM7nxnkyDZYg)

是只有这个 CDN 的资源拉取的时候会出问题吗？还是说还有其它的？如果只有这个 CDN 会出问题的话给我一个测试的 URL。

**Comment by zonefile** [comment]
Use `cdnjs.loli.net` or `s4.zstatic.net` instead, like `https://cdnjs.loli.net/ajax/libs/jquery/3.7.1/jquery.min.js` `https://s4.zstatic.net/ajax/libs/jquery/3.7.1/jquery.min.js`.

**Comment by LynxCatTheThird** [comment]
> 是只有这个 CDN 的资源拉取的时候会出问题吗？还是说还有其它的？如果只有这个 CDN 会出问题的话给我一个测试的 URL

StaticFile 和 BootCDN 所有的资源都会超时，测试链接如 `https://cdn.staticfile.net/jquery/3.7.1/jquery.min.js`

> Use `cdnjs.loli.net` or `s4.zstatic.net` instead

前段时间根据 EvanNotFound/hexo-theme-redefine/issues/347 换成南科大和 ZStatic 后没有再出现报错。

**Comment by LynxCatTheThird** [comment]
现在似乎没问题了？
![image](https://github.com/EmptyDreams/hexo-swpp/assets/103188954/2612caf2-d035-4cce-b607-6f418348b6d9)

> [sw-rules.js](https://github.com/LynxCatTheThird/web-v3/blob/main/sw-rules.js) 经过了多次更新，可能跟这也有关？
